### ISSUE TITLE
API down?

### ISSUE THREAD

**Issue by cheshire137** [maxkueng/somascrobbler#7]
Starting today, I haven't been able to connect a socket to the scrobbler API. I'm getting these errors in a shell:

```
% curl api.somascrobbler.com/api/v1/version
<html>
<head><title>503 Service Temporarily Unavailable</title></head>
<body bgcolor="white">
<center><h1>503 Service Temporarily Unavailable</h1></center>
<hr><center>nginx/1.11.0</center>
</body>
</html>
% curl http://api.somascrobbler.com/api/v1/nowplaying/defcon
<html>
<head><title>503 Service Temporarily Unavailable</title></head>
<body bgcolor="white">
<center><h1>503 Service Temporarily Unavailable</h1></center>
<hr><center>nginx/1.11.0</center>
</body>
</html>
```

Just wondering if you're doing something to the API, or if this is unexpected. Thanks!

**Comment by maxkueng** [comment]
Yeah, I'm working on it. Has to do with #6.

**Comment by maxkueng** [comment]
Uh, I mean maxkueng/somascrobbler-api#5

**Comment by cheshire137** [comment]
Thank you! 🙇

**Comment by maxkueng** [comment]
It's fixed and works again :tada:

@cheshire137 If you notice any future problems please report them in the [somascrobbler-api repo](https://github.com/maxkueng/somascrobbler-api/issues).

**Comment by cheshire137** [comment]
Can do, thanks!
